import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "../features/auth/AuthContext";

type Venue={id:string;name:string;city:string}; type Draft={id:string;title:string;status:string};
export function OrganiserPage(){
 const auth=useAuth(); const[venues,setVenues]=useState<Venue[]>([]); const[poster,setPoster]=useState(""); const[draft,setDraft]=useState<Draft|null>(null); const[status,setStatus]=useState("");
 useEffect(()=>{if(auth.user&&(auth.user.role==="organiser"||auth.user.role==="admin"))void auth.request<{data:Venue[]}>("/organiser/venues").then(r=>setVenues(r.data))},[auth]);
 if(!auth.user||(auth.user.role!=="organiser"&&auth.user.role!=="admin"))return <main className="placeholder"><h1>Organiser access required</h1></main>;
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const r=await auth.request<{data:{url:string}}>("/organiser/media/posters",{method:"POST",body:new FormData(e.currentTarget)});setPoster(r.data.url);setStatus("Poster uploaded.")}catch{setStatus("Poster upload failed. Check Cloudinary configuration.")}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const body={title:f.get("title"),description:f.get("description"),posterUrl:poster,trailerUrl:f.get("trailerUrl")||null,genres:String(f.get("genres")).split(",").map(x=>x.trim()).filter(Boolean),language:f.get("language"),durationMinutes:Number(f.get("durationMinutes")),ageRating:f.get("ageRating"),screenings:JSON.parse(String(f.get("screenings")))};const r=await auth.request<{data:Draft}>("/organiser/movies",{method:"POST",body:JSON.stringify(body)});setDraft(r.data);setStatus("Draft created. Review it, then submit for approval.")}catch{setStatus("Could not create draft. Check screening IDs, dates, and prices.")}}
 async function submit(){if(!draft)return;await auth.request(`/organiser/movies/${draft.id}/submit`,{method:"POST"});setDraft({...draft,status:"pending_approval"});setStatus("Submitted for admin approval.")}
 const screeningSample=JSON.stringify([{venueId:venues[0]?.id??"paste-venue-id",startsAt:new Date(Date.now()+86400000).toISOString(),prices:{standard:25000,premium:45000}}],null,2);
 return <main className="dashboard"><header><span className="eyebrow">ORGANISER</span><h1>Create a movie listing</h1></header><section className="dashboard-grid"><div className="dashboard-panel"><h2>1. Upload poster</h2><form className="auth-form" onSubmit={upload}><label>Poster image<input name="poster" type="file" accept="image/*" required/></label><button>Upload to Cloudinary</button></form>{poster&&<img className="poster-preview" src={poster} alt="Uploaded poster"/>}</div><div className="dashboard-panel"><h2>Available venues</h2>{venues.map(v=><div className="dashboard-row" key={v.id}><span><strong>{v.name}</strong><small>{v.city}</small></span><code>{v.id}</code></div>)}</div></section><section className="dashboard-panel"><h2>2. Movie and screenings</h2><form className="auth-form movie-form" onSubmit={create}><label>Title<input name="title" required/></label><label>Description<textarea name="description" required/></label><label>Genres<input name="genres" placeholder="Drama, Thriller" required/></label><label>Language<input name="language" required/></label><label>Duration<input name="durationMinutes" type="number" min="1" required/></label><label>Age rating<input name="ageRating" placeholder="UA 13+" required/></label><label>Trailer URL<input name="trailerUrl" type="url"/></label><label>Screenings JSON<textarea key={venues[0]?.id} name="screenings" defaultValue={screeningSample} required/></label><button disabled={!poster}>Create draft</button></form>{draft&&draft.status!=="pending_approval"&&<button className="standalone-action" onClick={()=>void submit()}>Submit “{draft.title}” for approval</button>}<p>{status}</p></section></main>;
}
