import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "../features/auth/AuthContext";

type Venue = { id: string; name: string; city: string; layout: { categories: { key: string; label: string }[] } };
type Screening = { id: string; venueName: string; startsAt: string; status: string; totalSeats: number; bookedSeats: number; activeHolds: number; bookingCount: number; revenuePaise: number };
type Movie = { id: string; title: string; description: string; posterUrl: string; trailerUrl?: string; genres: string[]; language: string; durationMinutes: number; ageRating: string; status: string; screenings: Screening[] };
type ScreeningForm = { venueId: string; startsAt: string; prices: Record<string, number> };

function blankScreening(venue?: Venue): ScreeningForm {
  return { venueId: venue?.id ?? "", startsAt: "", prices: Object.fromEntries(venue?.layout.categories.map(category => [category.key, 250]) ?? []) };
}

export function OrganiserPage() {
  const auth = useAuth();
  const [venues, setVenues] = useState<Venue[]>([]);
  const [movies, setMovies] = useState<Movie[]>([]);
  const [poster, setPoster] = useState("");
  const [draft, setDraft] = useState<Movie | null>(null);
  const [editing, setEditing] = useState<Movie | null>(null);
  const [addingTo, setAddingTo] = useState<Movie | null>(null);
  const [screeningForms, setScreeningForms] = useState<ScreeningForm[]>([]);
  const [newScreening, setNewScreening] = useState<ScreeningForm>({ venueId: "", startsAt: "", prices: {} });
  const [status, setStatus] = useState("");

  async function load() {
    if (!auth.user || (auth.user.role !== "organiser" && auth.user.role !== "admin")) return;
    const [venueResult, movieResult] = await Promise.all([auth.request<{ data: Venue[] }>("/organiser/venues"), auth.request<{ data: Movie[] }>("/organiser/movies")]);
    setVenues(venueResult.data); setMovies(movieResult.data);
    setScreeningForms(current => current.length ? current : [blankScreening(venueResult.data[0])]);
  }
  useEffect(() => { void load(); }, [auth.user]);
  if (!auth.user || (auth.user.role !== "organiser" && auth.user.role !== "admin")) return <main className="placeholder"><h1>Organiser access required</h1></main>;

  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const result = await auth.request<{ data: { url: string } }>("/organiser/media/posters", { method: "POST", body: new FormData(event.currentTarget) }); setPoster(result.data.url); setStatus("Poster uploaded."); } catch { setStatus("Poster upload failed. Check Cloudinary configuration."); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const screenings = screeningForms.map(screening => ({ venueId: screening.venueId, startsAt: new Date(screening.startsAt).toISOString(), prices: Object.fromEntries(Object.entries(screening.prices).map(([category, rupees]) => [category, Math.round(rupees * 100)])) })); const body = { title: form.get("title"), description: form.get("description"), posterUrl: poster, trailerUrl: form.get("trailerUrl") || null, genres: String(form.get("genres")).split(",").map(value => value.trim()).filter(Boolean), language: form.get("language"), durationMinutes: Number(form.get("durationMinutes")), ageRating: form.get("ageRating"), screenings }; const result = await auth.request<{ data: Movie }>("/organiser/movies", { method: "POST", body: JSON.stringify(body) }); setDraft(result.data); setStatus("Draft created. Review it, then submit for approval."); await load(); } catch { setStatus("Could not create draft. Check the screening dates and prices."); } }
  async function submit(movie: Movie) { await auth.request(`/organiser/movies/${movie.id}/submit`, { method: "POST" }); setStatus(`“${movie.title}” submitted for admin approval.`); await load(); }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const body = { ...editing, title: form.get("title"), description: form.get("description"), posterUrl: form.get("posterUrl"), trailerUrl: form.get("trailerUrl") || null, genres: String(form.get("genres")).split(",").map(value => value.trim()).filter(Boolean), language: form.get("language"), durationMinutes: Number(form.get("durationMinutes")), ageRating: form.get("ageRating") }; await auth.request(`/organiser/movies/${editing.id}`, { method: "PATCH", body: JSON.stringify(body) }); setEditing(null); setStatus("Movie updated."); await load(); }
  async function addScreening(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!addingTo) return; await auth.request(`/organiser/movies/${addingTo.id}/screenings`, { method: "POST", body: JSON.stringify({ venueId: newScreening.venueId, startsAt: new Date(newScreening.startsAt).toISOString(), prices: Object.fromEntries(Object.entries(newScreening.prices).map(([category, rupees]) => [category, Math.round(rupees * 100)])) }) }); setAddingTo(null); setStatus("Screening added."); await load(); }
  async function cancelScreening(screening: Screening) { if (!window.confirm("Cancel this screening and all of its confirmed bookings?")) return; await auth.request(`/organiser/screenings/${screening.id}`, { method: "DELETE" }); setStatus("Screening and affected bookings cancelled."); await load(); }

  function changeVenue(index: number, venueId: string) { const venue = venues.find(item => item.id === venueId); setScreeningForms(current => current.map((item, position) => position === index ? blankScreening(venue) : item)); }
  function setPrice(index: number, category: string, value: number) { setScreeningForms(current => current.map((item, position) => position === index ? { ...item, prices: { ...item.prices, [category]: value } } : item)); }
  function openAddScreening(movie: Movie) { setAddingTo(movie); setNewScreening(blankScreening(venues[0])); }
  return <main className="dashboard organiser-dashboard"><header><span className="eyebrow">ORGANISER</span><h1>Movies & screenings</h1><p>{status}</p></header>
    <section className="dashboard-panel"><h2>Managed movies</h2>{movies.map(movie => <article className="managed-movie" key={movie.id}><div className="managed-title"><div><span className="booking-status">{movie.status}</span><h3>{movie.title}</h3></div><div>{(movie.status === "draft" || movie.status === "rejected") && <><button className="secondary" onClick={() => setEditing(movie)}>Edit</button><button onClick={() => void submit(movie)}>Submit</button></>}<button onClick={() => openAddScreening(movie)}>Add screening</button></div></div><div className="managed-screenings">{movie.screenings.map(screening => <div className={`screening-stat ${screening.status}`} key={screening.id}><strong>{new Date(screening.startsAt).toLocaleString("en-IN")}</strong><span>{screening.venueName}</span><small>{screening.bookedSeats}/{screening.totalSeats} seats booked · {screening.activeHolds} held</small><small>{screening.bookingCount} bookings · ₹{(screening.revenuePaise / 100).toFixed(0)} revenue</small>{screening.status === "scheduled" && new Date(screening.startsAt) > new Date() && <button className="danger" onClick={() => void cancelScreening(screening)}>Cancel screening</button>}</div>)}</div></article>)}</section>
    {editing && <section className="dashboard-panel"><h2>Edit “{editing.title}”</h2><form className="auth-form movie-form" onSubmit={update}><label>Title<input name="title" defaultValue={editing.title} required/></label><label>Description<textarea name="description" defaultValue={editing.description} required/></label><label>Poster URL<input name="posterUrl" defaultValue={editing.posterUrl} required/></label><label>Genres<input name="genres" defaultValue={editing.genres.join(", ")} required/></label><label>Language<input name="language" defaultValue={editing.language} required/></label><label>Duration<input name="durationMinutes" type="number" defaultValue={editing.durationMinutes} min="1" required/></label><label>Age rating<input name="ageRating" defaultValue={editing.ageRating} required/></label><label>Trailer URL<input name="trailerUrl" type="url" defaultValue={editing.trailerUrl}/></label><button>Save changes</button></form></section>}
    {addingTo && <section className="dashboard-panel"><h2>Add screening for “{addingTo.title}”</h2><form className="auth-form movie-form" onSubmit={addScreening}><label>Venue<select value={newScreening.venueId} onChange={event => setNewScreening(blankScreening(venues.find(venue => venue.id === event.target.value)))}>{venues.map(venue => <option key={venue.id} value={venue.id}>{venue.name}, {venue.city}</option>)}</select></label><label>Starts at<input value={newScreening.startsAt} onChange={event => setNewScreening(current => ({ ...current, startsAt: event.target.value }))} type="datetime-local" required/></label><div className="price-fields">{venues.find(venue => venue.id === newScreening.venueId)?.layout.categories.map(category => <label key={category.key}>{category.label} price (₹)<input type="number" min="1" value={newScreening.prices[category.key] ?? 250} onChange={event => setNewScreening(current => ({ ...current, prices: { ...current.prices, [category.key]: Number(event.target.value) } }))} required/></label>)}</div><button>Add screening</button></form></section>}
    <section className="dashboard-grid"><div className="dashboard-panel"><h2>1. Upload poster</h2><form className="auth-form" onSubmit={upload}><label>Poster image<input name="poster" type="file" accept="image/*" required/></label><button>Upload to Cloudinary</button></form>{poster && <img className="poster-preview" src={poster} alt="Uploaded poster"/>}</div><div className="dashboard-panel"><h2>Available venues</h2>{venues.map(venue => <div className="dashboard-row" key={venue.id}><span><strong>{venue.name}</strong><small>{venue.city}</small></span><code>{venue.id}</code></div>)}</div></section>
    <section className="dashboard-panel"><h2>2. Create movie and screenings</h2><form className="auth-form movie-form" onSubmit={create}><label>Title<input name="title" required/></label><label>Description<textarea name="description" required/></label><label>Genres<input name="genres" placeholder="Drama, Thriller" required/></label><label>Language<input name="language" required/></label><label>Duration<input name="durationMinutes" type="number" min="1" required/></label><label>Age rating<input name="ageRating" placeholder="UA 13+" required/></label><label>Trailer URL<input name="trailerUrl" type="url"/></label><div className="screening-builder"><h3>Screenings</h3>{screeningForms.map((screening,index) => <fieldset key={index}><label>Venue<select value={screening.venueId} onChange={event => changeVenue(index,event.target.value)}>{venues.map(venue => <option key={venue.id} value={venue.id}>{venue.name}, {venue.city}</option>)}</select></label><label>Starts at<input type="datetime-local" value={screening.startsAt} onChange={event => setScreeningForms(current => current.map((item,position) => position===index?{...item,startsAt:event.target.value}:item))} required/></label><div className="price-fields">{venues.find(venue => venue.id===screening.venueId)?.layout.categories.map(category => <label key={category.key}>{category.label} price (₹)<input type="number" min="1" value={screening.prices[category.key]??250} onChange={event => setPrice(index,category.key,Number(event.target.value))} required/></label>)}</div>{screeningForms.length>1&&<button type="button" className="remove-screening" onClick={()=>setScreeningForms(current=>current.filter((_,position)=>position!==index))}>Remove screening</button>}</fieldset>)}<button type="button" className="secondary" onClick={()=>setScreeningForms(current=>[...current,blankScreening(venues[0])])}>Add another screening</button></div><button disabled={!poster||!screeningForms.length}>Create draft</button></form>{draft && draft.status !== "pending_approval" && <button className="standalone-action" onClick={() => void submit(draft)}>Submit “{draft.title}” for approval</button>}</section>
  </main>;
}
